### ISSUE TITLE
Ponyframe server error.

### ISSUE THREAD

**Issue by Xayaan** [lipp/ponyframe-issues#1]
![ponyframe](https://cloud.githubusercontent.com/assets/5237930/11283968/21c433ba-8f29-11e5-9083-a06b255f9634.png)

Hey there, as shown in the screenshot above, I tried rendering alot of websites, including google.com but the same error persists. I tried a proxy too.

**Comment by lipp** [comment]
@Xayaan thanks for reporting. Sorry for the inconvenience! Many popular websites block embedding into iframes (google.com, yahoo.com, bbc.co.uk)
This means the  X-Frame-Options http header is set to SAMEORIGIN. This prevents the targeted website (e.g. google.com) to be displayed within iframes and thus prevents displaying on ponyfame.com.
Your proxy probably does not change this header, so the X-Frame-Options: SAMEORIGIN is still set.

**Comment by Xayaan** [comment]
Thank you!
